import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import categoriesRouter from "./categories";
import productsRouter from "./products";
import cartRouter from "./cart";
import ordersRouter from "./orders";
import bannersRouter from "./banners";
import couponsRouter from "./coupons";
import analyticsRouter from "./analytics";
import wishlistRouter from "./wishlist";
import reviewsRouter from "./reviews";
import addressesRouter from "./addresses";
import usersRouter from "./users";
import notificationsRouter from "./notifications";
import returnsRouter from "./returns";
import flashSalesRouter from "./flash-sales";
import loyaltyRouter from "./loyalty";
import walletRouter from "./wallet";
import productQaRouter from "./product-qa";
import deliveryRouter from "./delivery";
import newsletterRouter from "./newsletter";
import referralsRouter from "./referrals";
import exportRouter from "./export";
import settingsRouter from "./settings";
import paymentsRouter from "./payments";
import pushRouter from "./push";
import subscriptionsRouter from "./subscriptions";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(categoriesRouter);
// product-qa routes with :productId param must be registered before products/:id
router.use(productQaRouter);
router.use(productsRouter);
router.use(cartRouter);
router.use(ordersRouter);
router.use(bannersRouter);
router.use(couponsRouter);
router.use(analyticsRouter);
router.use(wishlistRouter);
router.use(reviewsRouter);
router.use(addressesRouter);
router.use(usersRouter);
router.use(notificationsRouter);
router.use(returnsRouter);
router.use(flashSalesRouter);
router.use(loyaltyRouter);
router.use(walletRouter);
router.use(deliveryRouter);
router.use(newsletterRouter);
router.use(referralsRouter);
router.use(exportRouter);
router.use(settingsRouter);
router.use(paymentsRouter);
router.use(pushRouter);
router.use(subscriptionsRouter);

export default router;
