import { createRequire } from "node:module";
import path from "node:path";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { db, pool } from "@workspace/database";

// Versioned migrations live in the database package (`packages/database/migrations`),
// generated by `drizzle-kit generate`. Resolve that folder relative to the
// installed `@workspace/database` package so this runner works from anywhere.
const require = createRequire(import.meta.url);
const dbEntry = require.resolve("@workspace/database");
const migrationsFolder = path.join(path.dirname(dbEntry), "..", "migrations");

async function main() {
  console.log(`🔄 Applying versioned migrations from ${migrationsFolder} ...`);
  await migrate(db, { migrationsFolder });
  console.log("✅ Migrations applied successfully!");
}

main()
  .catch((err) => {
    console.error("❌ Migration failed:", err);
    process.exitCode = 1;
  })
  .finally(async () => {
    await pool.end();
  });
